# Jupyter Lab configuration
[JUPYTER]
# Set to true to start Jupyter Lab
# Set to false to connect to an existing Jupyter Lab instance
START_JUPYTER = true
# port of Jupyter Lab in localhost
JUPYTER_PORT = 8888

[PROMPT]
# Name of the prompt template file (all files in `prompt/`)
PROMPT_TEMPLATE = "general"